version: 2

jobs:

  build:

    working_directory: ~/MedvedevYuriy/hubot

    parallelism: 1

    shell: /bin/bash --login
    
    environment:

      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts

      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:

    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37

      command: /sbin/init

    steps:

    - checkout

    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    - restore_cache:

        keys:

        - v1-dep-{{ .Branch }}-

        - v1-dep-master-

        - v1-dep-

    - run: |
        curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -

        sudo apt update

        sudo apt-get install -y nodejs

        nodejs --version

        npm --version

    - run: |-

        npm install -g yo generator-hubot

        mkdir myhubot

        cd myhubot

        yo hubot --defaults

    - save_cache:

        key: v1-dep-{{ .Branch }}-{{ epoch }}

        paths:

        - vendor/bundle

        - ~/virtualenvs

        - ~/.m2

        - ~/.ivy2

        - ~/.bundle

        - ~/.go_workspace

        - ~/.gradle

        - ~/.cache/bower

        - ./node_modules

    - run: npm test

    - store_test_results:

        path: /tmp/circleci-test-results

    - store_artifacts:

        path: /tmp/circleci-artifacts

    - store_artifacts:

        path: /tmp/circleci-test-results
